### ISSUE TITLE
Getting the issue 422  while pulling github.com/mattn/goveralls 

### ISSUE THREAD

**Issue by asellappen** [agext/levenshtein#4]
package levenshtein  failing as bwlow when it tried to access github.com/mattn/goveralls 
https://travis-ci.com/github/asellappen/levenshtein/jobs/398770419

Testing with goveralls...
go: downloading github.com/mattn/goveralls v0.0.7
go: github.com/mattn/goveralls upgrade => v0.0.7
go: downloading golang.org/x/tools v0.0.0-20200522201501-cb1345f3a375
Bad response status from coveralls: 422
{"message":"Couldn't find a repository matching this job.","error":true}
The command "./test.sh $TEST_METHOD" exited with 1.

 have tried with adding COVERALLS_TOKEN in travis.yml as below and still its failing ,
  travis encrypt COVERALLS_TOKEN=your_token_goes_here --add env.global
env:
  global:
    secure: 0wWHj9zvAqpjPMxngeVm6+WwjynAAfOwoGy1yBnwiH7rsOskuWbf7aaaOhVC65fH+wiRbmBIpGMlVXv5wrKGrK7EXxMcoXBtie0MoK2UCWRwJcYG3+e4bZ9wLe+3eBRGK/EbT8GawHrJaZxPvhg......................................
	
Please help to check and provide a fix for this?

**Comment by alex-alrux** [comment]
That seems to be an issue with your fork and coveralls.io not being able to access it. Sorry, cannot help you with troubleshooting your CI setup/configuration, but we just ran again the tests and it's all good on this repo:
https://travis-ci.org/github/agext/levenshtein
